# Generated by Django 4.0.4 on 2022-06-05 16:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Given Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('age', models.CharField(max_length=200, verbose_name='Age of Missing Person')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200, verbose_name='Gender of Missing Person')),
                ('last_seen', models.CharField(max_length=200, verbose_name='Last Seen Location')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Any Other Important Details')),
                ('photo', models.ImageField(upload_to='missingpersons/', verbose_name='Upload Photo of Missing Person')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Contact Person')),
                ('contact_relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Guardian', 'Guardian'), ('Relative', 'Relative'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=200, verbose_name='Relationship with Missing Person')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Contact Number')),
                ('status', models.CharField(choices=[('New', 'New'), ('Leads', 'Leads'), ('Found', 'Found'), ('Closed', 'Closed')], default='New', max_length=200, verbose_name='Current Status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Person Background Check Done?')),
                ('face_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Face ID of Missing Person')),
                ('found_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Found Location')),
                ('found_time', models.DateTimeField(blank=True, null=True)),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Contact person has been informed?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mising People',
                'verbose_name_plural': 'Missing People',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='ReportedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_location', models.CharField(max_length=200, verbose_name='Found Location')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Any Other Important Details')),
                ('photo', models.ImageField(upload_to='reportedpersons/', verbose_name='Upload Photo of Reported Person')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is this valid reporting?')),
                ('face_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Face ID of Reported Person')),
                ('is_matched_with_missing_person', models.BooleanField(default=False, verbose_name='Has the match found?')),
                ('matched_confindence', models.CharField(blank=True, max_length=200, null=True, verbose_name='Details of Match')),
                ('matched_face_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Face ID of Matched Person')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reported People',
                'verbose_name_plural': 'Reported People',
                'ordering': ('created_date',),
            },
        ),
    ]
